name: Run CS on pull requests

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  cs:
    name: Run composer cs
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: ['8.0', '8.1', '8.2']

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-php@v4
        with:
          php-version: ${{ matrix.php-version }}

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Run CS script
        run: composer run-script cs
